package:
  name: php-frankenphp-8.2-tideways
  version: 5.9.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: Proprietary
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 112e5cb2410bb47efef8aee4a4acd2008dde61d8bf73828e39d18a3214ddf9df4a648db8a1460b6cc3e17d01af47fe0a66b6989b72770e7cfa4be2496c3ad696

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 0a191307511b0f5f9a49ca40892b480012c3d14beb3ec9f5d2ac061f7fea90c6253566969abb6d574839d8bfa012b72fc23c61b5e1e6b684bbb1bcf01934286b

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.2-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
