package:
  name: php-frankenphp-8.2-tideways
  version: 5.8.4
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: Proprietary
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 2a01382a898c350580593005984aef40d5b3735dc1e85752a4907fde5bd2b23a2b30eb01c313bfa56c3fbb40eb77a20df2f29de1e73413ba6ab764d4929729c7

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: b748b958e248a70119dd350580a923e9895ab125c66b6d0cb976a99a6eb5ff2d7468e54ab08c9453689501a00e58829c67a81002d9b27c4a0858deb7d2b04941

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.2-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
