name: Build docker image
on:
    schedule:
      - cron: '4 0 * * *'
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - Dockerfile

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login into Github Docker Registery
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - uses: docker/build-push-action@v5
              with:
                tags: ghcr.io/friendsofshopware/wolfi-php:latest
                platforms: linux/amd64,linux/arm64
                push: true
                provenance: false
